### ISSUE TITLE
webP 动态支持

### ISSUE THREAD

**Issue by NObodyGX** [QL-Win/QuickLook#1024]
使用时发现对于 webp 仅仅支持静态图片，并没有支持动态图片，请问这个有计划支持吗？

**Comment by Cdddo** [comment]
Bumping this. Really need animated webp. Browser constantly forcing the use of webp and windows barely supporting it is a constant pain.

**Comment by NaitorStudios** [comment]
Seeing this I guess there's no hope if I don't manage to make it work myself...

**Comment by mooflu** [comment]
I wrote a [plugin ](https://github.com/mooflu/QuickLook.Plugin.WebViewPlus) a while back to preview a bunch of formats via [WebView2](https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes?tabs=dotnetcsharp). If you don't mind the higher resource usage due to browser preview, it supports the various web image formats just like Edge. Plugin uses [this web app](https://github.com/mooflu/WebViewPlus) so you can try it first in your browser.

**Comment by emako** [comment]
Done, BUT Limitations: Only supports x64 systems.
