### ISSUE TITLE
Preview from Open and Save File Dialog not working

### ISSUE THREAD

**Issue by AnweshGangula** [QL-Win/QuickLook#1028]
**Describe the bug**
Pressing spacebar in and Open or Save File Dialog doesn't do anything. The Preview window doesn't show up. It's working fine in Desktop and Default File Explorer and also in "Everything".

**To Reproduce**
press spacebar on any supported file formats in a Open or Save File Dailog

**Expected behavior**
default quicklook behavior - preview the file

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Enterprise - 19042.1237
 - QuickLook Version: v3.7.0 fromm Chocolatey (.msi)

**Comment by florinb19** [comment]
@xupefei this happens for me too on the latest .msi version, W10 21H1 build 19043.1288

**Comment by Dhyfer1** [comment]
@xupefei Is there any progress for this issue? I also have the same problem on Windows 11 64bits with the latest build (22000.318). The preview in Open/Save dialog boxes is not working in the latest version of Quicklook. 😔

**Comment by xupefei** [comment]
But it works for me.

**Comment by xupefei** [comment]
Note that QL will not work in dialogs opened by a application running as admin.

**Comment by Dhyfer1** [comment]
@xupefei I don't understand why it is not working. I don't know if it is working in any specific version, in my case I installed Quicklook (stable version) through the .msi file in Windows 11 Pro 64bits. With the Paint app and its Open dialog box, I have tried using a .jpg image file to display with QL, but when I select the image and press Space to display it within the dialog, QL simply does not open. :(
@AnweshGangula Do you still have the same problem?

**Comment by xupefei** [comment]
> @xupefei I don't understand why it is not working. I don't know if it is working in any specific version, in my case I installed Quicklook (stable version) through the .msi file in Windows 11 Pro 64bits. With the Paint app and its Open dialog box, I have tried using a .jpg image file to display with QL, but when I select the image and press Space to display it within the dialog, QL simply does not open. :( @AnweshGangula Do you still have the same problem?

See the first comment in this issue: https://github.com/QL-Win/QuickLook/issues/1028#issuecomment-953777455.
Does it solve your problem?

**Comment by AnweshGangula** [comment]
> @AnweshGangula Do you still have the same problem?
Yes, this is still an issue for me.

**Comment by Dhyfer1** [comment]
> See the first comment in this issue: [#1028 (comment)](https://github.com/QL-Win/QuickLook/issues/1028#issuecomment-953777455). Does it solve your problem?

Hello again. I have downloaded the QL version from AppVeyor and if it is working the visualization of files in dialog boxes 😊, so the problem comes with the stable version and I hope that the next update of QL stable you can fix that bug; apart from that, I hope you can also fix that the background of text files can be seen in dark theme (currently the background is seen in gray color) when Windows is with the dark theme.

That's all.

P.S. By the way, is it possible to change the space key to another key to open QL?

**Comment by djcurley89** [comment]
This fixed it for me as well

> Could you try https://ci.appveyor.com/project/xupefei/quicklook/builds/41189683/artifacts?

**Comment by xupefei** [comment]
See https://github.com/QL-Win/QuickLook/issues/272.

**Comment by Dhyfer1** [comment]
> See #272.

@xupefei I had seen this issue before and saw your comment. https://github.com/QL-Win/QuickLook/issues/272#issuecomment-433686549 but it is no longer possible to see the two web pages indicated there, they are down. That's why I need your help to know how to change the space key for another key to run QL. Please.

**Comment by rabelux** [comment]
@Dhyfer1 Pls continue that discussion in the appropriate thread. This issue is about file dialogs.
