### ISSUE TITLE
App don't work when running Everything using Task Scheduler

### ISSUE THREAD

**Issue by arindam0708** [QL-Win/QuickLook#1038]
In order keep startups relatively fast use Task Scheduler to run Everything Search.  [Everything.exe - startup]

This does not seem to work that way.
everything is enabled as service.
still it doesn't work.

**Comment by rabelux** [comment]
Sounds like a problem with everything to me - no mention of QuickLook.

**Comment by arindam0708** [comment]
I believe I may not have been able to explain the issue properly.

When using task scheduler to run [Everything.exe -startup] QuickLook doesn't show any previews. But the same application (Everything) when runs by default on startup, QuickLook works just fine. 

I am not sure where the issue is.The workaround for the are :

- I've to either close the Everything process and start the application again.

- Or instead of using Task Scheduler to run the application in background, use the default settings within Everything to run the app on startup. 

Ideally when trying to preview files (using 
QuickLook) inside Everything Search, it works without an issue.

I'm aware the Everything should be _installed as service_ in order to use QuickLook inside Everything. 
QuickLook is running on background while trying to preview from Everything.

**Comment by rabelux** [comment]
Have a look at #533. Everything may not be started with administrator rights and I guess that's what your task scheduler does.

**Comment by ariefcfa** [comment]
Hi, just sharing what worked for me. Please follow the steps at [Using space bar](https://www.voidtools.com/forum/viewtopic.php?t=10510). I use Windows's Task Scheduler too to start Everyting service, and the task must run as admin otherwise I can't start the service.

The Task Scheduler is configured as below:
**General** tab:

- Run with the highest privileges = **checked**

**Action** tab:

- Program/script: `sc`
- Add arguments (optional): `start "Everything"`

QuickLook works when Everything running without [the Everything alpha instance](https://www.voidtools.com/forum/viewtopic.php?f=12&t=10012#p36726).
