### ISSUE TITLE
After starting quicklook, the program will exit automatically when the mouse points to the taskbar icon

### ISSUE THREAD

**Issue by HBJ008** [QL-Win/QuickLook#1061]
My system is Windows 11 and I was using quicklook normally before, today I was prompted to update to version 3.7.1, so I downloaded the free install version.
After overwriting and unzipping, I opened the program and a small icon appeared in the bottom right corner of the taskbar and the system prompted that quicklook was running in the background.
But when I select a text file and press space button, the preview window does not pop up and when I point my mouse to the quicklook icon in the bottom right corner, the icon automatically disappears and the program flashes back without any indication.

**Comment by rabelux** [comment]
Did you quit QL before installing the update? Did you install in the same directory? Did you reboot?

If all of the above questions can be answered with *yes* please provide logs. Location is listed in the wiki.

**Comment by xupefei** [comment]
> unzipping

I assume you're using the ZIP version. Please check if you have done this step: https://github.com/QL-Win/QuickLook/issues/1

**Comment by iduangy** [comment]
I think you should use the portable "zip" version, and use the decompressed file of the new version to directly overwrite the upgraded one.
This problem should be caused by a plug-in conflict. Enter the program "QuickLook\QuickLook.Plugin" plug-in folder and delete the following folder should be resolved.
![image](https://user-images.githubusercontent.com/75022553/147334657-b75f5932-a670-487e-a4c6-194f02b53c59.png)

**Comment by rabelux** [comment]
Closed due to inactivity.
