### ISSUE TITLE
Where to download a nightly build?

### ISSUE THREAD

**Issue by L1cardo** [QL-Win/QuickLook#1262]
**Describe the bug**
There is no any any artifacts on appveyor website.

**Screenshots and Exception Log**
![image](https://user-images.githubusercontent.com/33802186/216800203-9ed0956b-cdc3-4535-ad62-01741e1c141b.png)

**Comment by hltdev8642** [comment]
@L1cardo , I can't say for sure but I took a look at the build output and it seems it _may_ be the same version available on github releases (says: `QuickLook-3.7.3-15-g1d566c9.msi` / `QuickLook-3.7.3-15-g1d566c9.zip`). My guess would be that maybe the dev is not leaving those nightly releases available any longer because there aren't any that are ahead of the version available via gh releases.

**Comment by emako** [comment]
https://github.com/QL-Win/QuickLook/releases
