### ISSUE TITLE
PDFs show up very small in preview

### ISSUE THREAD

**Issue by sciulli999** [QL-Win/QuickLook#143]
Just got a Surface Book 2 and QuickLook was one of my most missed features from macOS. Thank you for your project here.

Everything seems to be pretty good except for PDFs. They seem to appear very small. Any way to fix this?

![pdfsmall](https://user-images.githubusercontent.com/34143379/33457191-b83662dc-d5ef-11e7-9c12-513d01a52fd0.JPG)

**Comment by xupefei** [comment]
You can always use Ctrl+Wheel to zoom it.

BTW, the PDF viewer window is quite small in version 0.2.3.1. In the next release, it will be larger. You can also try the latest nightly version from [AppVeyor](https://ci.appveyor.com/project/xupefei/quicklook/build/artifacts).

**Comment by demolitionb** [comment]
still too small. Especially for PDF documents with small dimensions (physical).
Since those files are vector-files in my case, zooming is not a problem, but the preview window is too small. I think for bitmaps etc. that makes sense, but not for vector grafics.

The window of quicklook could be always 70-80% of the screen in this case (pdf, svg, ps, eps, ...)

**Comment by xupefei** [comment]
@demolitionb Could you give me an example?

**Comment by demolitionb** [comment]
@xupefei : 
[GeometrieStreuung.pdf](https://github.com/xupefei/QuickLook/files/1614168/GeometrieStreuung.pdf)

**Comment by xupefei** [comment]
@demolitionb Please try the latest nightly version and give any feedback here :)

**Comment by demolitionb** [comment]
it's better now, but maybe:
_maxZoomFactor = 5 * factor;
should be something like 7 ? It still could be slightly larger. (as far I understood the formula)

another nice feature would be, that the zooming enlarges the window canvas too instead of zooming and cropping into the current window canvas. Of course, just until it reaches the max. dimensions that are possible. It's for example implemented in ImageJ / FIJI ... I will open another ticket for that.

**Comment by xupefei** [comment]
TODO for myself: `_maxZoomFactor` should be related to page dimension, for example,
_maxZoomFactor = 5000d /  Math.Min(page.Width, page.Height)

**Comment by mattsigal** [comment]
I am in a similar situation - just installed QuickLook and was hoping to find a way to make my PDF previews larger. Is there some way to make the QL window larger by default? For instance, here is the original window:

![ql](https://user-images.githubusercontent.com/1421758/35168433-c79bd55a-fd0d-11e7-9690-e4ac80bdc0fe.PNG)

And here is another QL instance that I manually enlarged/zoomed in on:

![ql2](https://user-images.githubusercontent.com/1421758/35168441-d2417e9c-fd0d-11e7-8aba-97dcf2574092.PNG)

Is it be possible to have that happen by default? I can't seem to find any configuration options for the app.

**Comment by xupefei** [comment]
@mattsigal The latest Nightly version handles this better, you can have a try.
