### ISSUE TITLE
Configurable action key (space)

### ISSUE THREAD

**Issue by rseiler** [QL-Win/QuickLook#272]
In the file explorer it's possible to jump to a specific item (folder/file) if you just typing it's name. E.g. "test 3" to jump to this file. But with this APP running it opens the preview for the "test 1" file. I imagine that not many people are using this feature and therefore the space key works just fine. Nevertheless it would be great to give the possibility to change the key to something like "ctrl + space". Then the preview and the "jump to an item" would work without interference.

**Comment by McNEET** [comment]
I prefer to use ctrl cause I've set a shortcut for ctrl in my mouse.
p.s. double ctrl opens search-bar of Listary, so ctrl is my nessesery shortcut on mouse.

**Comment by xupefei** [comment]
The aim of this project is to copy macOS _Quick Look_ experiences to Windows. I don't want to make it too complicated.

I suggest you modify the key by yourself since it is quite easy. Just modify `Keys.Space` https://github.com/QL-Win/QuickLook/blob/master/QuickLook/BackgroundListener.cs#L98 and https://github.com/QL-Win/QuickLook/blob/master/QuickLook/BackgroundListener.cs#L112 to something else.

**Comment by McNEET** [comment]
> The aim of this project is to copy macOS _Quick Look_ experiences to Windows. I don't want to make it too complicated.
> 
> I suggest you modify the key by yourself since it is quite easy. Just modify `Keys.Space` https://github.com/QL-Win/QuickLook/blob/master/QuickLook/BackgroundListener.cs#L98 and https://github.com/QL-Win/QuickLook/blob/master/QuickLook/BackgroundListener.cs#L112 to something else.

OK, i'll try it, thank you very much! !
btw, how to make it auto show/hide in several sec. after mouse hovering? thank you for reply me_i'm just a layman...

**Comment by xupefei** [comment]
That is unfortunately not possible.

**Comment by rabelux** [comment]
@Dhyfer1 you can search for issues and eventually you would have found any of the three existing issues regarding your topic.

**Comment by rabelux** [comment]
The file moved to https://github.com/QL-Win/QuickLook/blob/master/QuickLook/KeystrokeDispatcher.cs

**Comment by Dhyfer1** [comment]
@xupefei I had seen this issue before and saw your comment. #272 (comment) but it is no longer possible to see the two web pages indicated there, they are down. That's why I need your help to know how to change the space key for another key to run QL. Please. 

P.S. I am not a developer or programmer, so I have no idea how to modify the keystrokedispatcher.cs file indicated by rabelux.

**Comment by Chris2011** [comment]
As you can see there are some people who wants to change the hotkey via settings. The problem by changing it by our own, doesn't mean that after an update of the plugin will override it? So if yes, this is not an option. The current behavior is for some people not practiable enough. So at the end, maybe just a settings file w/o a big settings UI could be enough for an MVP. What do you think?
