### ISSUE TITLE
Switch to NConvert

### ISSUE THREAD

**Issue by xupefei** [QL-Win/QuickLook#300]
Switch to NConvert.
Related to #278.

**Comment by TheStruggleForAntiSpaghetti** [comment]
Do I understand correctly from this that you are converting files to a temp file(type) that your viewer knows natively to not having to implement other types?

**Comment by xupefei** [comment]
Yes. NConvert can handle almost all types of image files. And it's fast.

**Comment by TheStruggleForAntiSpaghetti** [comment]
While I understand the convenience and security because you don't have to implement file-types yourself, it does mean that it slows down viewing files (read-convert(write)-read-show) and creates extra writes to SSDs.
Wouldn't it be better for the purpose of speed and not having to use temp-files if it could just natively and directly read and show the files in memory?
Or are you doing that with most-common filetypes and going to use NConvert for others?

What is your stance on a plugin-based QuickLook where the community can develop those plugins? The framework being to read and decode files and pass it on to QuickLook to show it but all in-memory (so without using temp-files).

Thanks :)

**Comment by xupefei** [comment]
> if it could just natively and directly read and show the files in memory

Sure. NConvert can uses stdout instead of temp files. So there will not have any SSD write.

> Or are you doing that with most-common filetypes and going to use NConvert for others?
> 

NConvert is a decoder/encoder for images. It will be used only for the ImageViewer, replacing Magick.NET/ImageMagick and exiv2.

> What is your stance on a plugin-based QuickLook where the community can develop those plugins?
> 
Any contribution is welcome. QL is now already plugin-based, except a convinient way to allow users installing more plugins. I have a plan on this but haven’t do it since there are, in fact, no any other plugin available outside this repo :-(

Cheers,
Paddy

**Comment by TheStruggleForAntiSpaghetti** [comment]
Thanks for the insight :)


> QL is now already plugin-based

I saw now when having a further look :)


>  I have a plan on this but haven’t do it since there are, in fact, no any other plugin available outside this repo :-(

Could creating a separate plugin template and documentation help? That way you possibly make it more accessible. And people interested in writing plugins could just use that as a base and write them without having to touch the main code.

**Comment by xupefei** [comment]
> Could creating a separate plugin template and documentation help?

I added it to the to-do list.

**Comment by jeremyhart** [comment]
A plugin template and documentation would be great, there's a bunch of file types I want to make plugins for but I'm having trouble building ATM.
