### ISSUE TITLE
QuickLook only shows blank window

### ISSUE THREAD

**Issue by JohnKJohnson** [QL-Win/QuickLook#405]
I installed QuickLook today, and since the beginning the preview didn't work. It only shows a blank window, no matter what file I selected.

![quicklooknoworki](https://user-images.githubusercontent.com/44440161/47439846-66deed80-d7ad-11e8-8dd6-8b0cd60f633e.jpg)

The size of the window changes with each file, though, and I can close it whenever I click on the top right corner. Seems like the graphics are invisible but the functions are 'there'.

I tried the store version, the msi version (3.6.2) and the nightly. Nothing changed, same behaviour in all of them.

I have Windows 10 Pro 1803. No QuickLook.Exception.log available, only config files.

**Comment by xupefei** [comment]
What graphics card are you using now?

**Comment by JohnKJohnson** [comment]
Intel HD Graphics 3000

**Comment by xupefei** [comment]
It is due to driver issue.

The last comment in https://github.com/QL-Win/QuickLook/issues/255 says that

> 经过确认，原因是目前的1803系统和Intel核显驱动不兼容，已经回滚，问题解决

In English: After testing, I confirmed that there is a compatibility issue between Windows 10 1803 and Intel Graphics driver. I have rolled back the xxx (system? driver? he does not specify here clearly) then the issue is resolved.
