### ISSUE TITLE
关于3.6.2版预览图片的若干问题。

### ISSUE THREAD

**Issue by TaicEart** [QL-Win/QuickLook#417]
系统是 Win8.1。

### 能只让 QuickLook 崩溃的特定 .png
由我转达的问题。
有人发现自己软件存储用 .png 几乎必定导致且仅导致 QuickLook 崩溃或卡死超过1分钟，卡的途中不能切换预览其他文件（此外任意软件阅览下图都不会崩溃，Seer 0.8.1 亦然。下图只是随便生成的例图）。
![crash](https://user-images.githubusercontent.com/19991045/47837230-37039b80-dde6-11e8-8e1c-1a4e214a56d8.png)
对图片转换会导致软件存储特有信息损失，所以不能转换图片来迁就 QuickLook。

### 浏览小图不应放大
是这样的场景：我创作图标/界面用图需要预览实际尺寸。
不过，如果 QuickLook 设计是必须放大我也接受，但不能反锯齿，尤其是像素图，反锯齿会显示非常糟。

### 奇怪的显示窗口
预览图片有时会在左右/上下留出透明空间，也有时会上下收缩导致出现滚动条——而且还经常是小的 .gif。
我原以为是连续浏览不同分辨率的图片导致，但单独预览也会出现。这种情况没找到规律。

### .psd 预览明显比较慢
3MB 以内透明背景的 .psd，QuickLook 有个模糊到清晰的过程，约1~2秒。相对的，Seer 0.8.1 则能瞬开，与预览同尺寸 .png 无差别，不知怎么做到的。

---

### 能否给出文本类文档的源代码预览开关
我对 .html 的渲染后预览需求不高（主要是我这电脑上 QuickLook 渲染网页很慢……），但很需要预览 .html 着色代码。 
与 #123 有重复，不过我的要求类似 #336 ，希望能有配置文件可以设置默认对某个格式优先预览代码而不渲染。

**Comment by xupefei** [comment]
This is because that app is producing PNGs containing a lot of `mkBT` chunks.
To determine if a PNG is APNG, one need to search `acTL` string in a file. The previous search algorithm is slow for huge files.

The nightly build should have fixed the problem: https://ci.appveyor.com/project/xupefei/quicklook/builds/19988169/artifacts

![image](https://user-images.githubusercontent.com/1687847/47882553-912a4e00-de32-11e8-8c35-ce8e858a7c81.png)
