### ISSUE TITLE
I use it to preview images in svg format, it only shows internal code. Please support both .svg and .eps vector formats

### ISSUE THREAD

**Issue by FanXiangTM** [QL-Win/QuickLook#488]
*For all's convenience, please use English to fill this issue.*

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by StefanKrapf** [comment]
I would totally agree with this. I Need previews of EPS files too. SVG would be even nice. Thanks a lot for considering to integrate it.

**Comment by frogdesk** [comment]
One option would be to uninstall QuickLook and use Seer. That is what I have had to do. Dropping SVG support was an extremely unfortunate decision.

**Comment by xupefei** [comment]
Well, this is because I have switched from ImageMagick (with which you can view SVG images) to NConvert (with which you can't) sometime before because the former one does not handle colour profile and RAW images well.

My idea now is to write a standalone SVG plugin. I already found one good library: https://github.com/ElinamLLC/SharpVectors but I have no time to integrate it. Nevertheless, I believe it is fairly simple (to an extent similar to [this one](https://github.com/jeremyhart/QuickLook.Plugin.HelixViewer)) to even a half-year-experience C# developer. Any volunteer want to do it?

**Comment by albertshaw** [comment]
@xupefei  Why not use your HtmlViewer to preview SVG file, just like what you did in MarkdownViewer?

**Comment by xupefei** [comment]
@albertshaw Bingo! I hadn't thought that SVG can be viewed as a webpage. I will fix this right away.

**Comment by rabelux** [comment]
Are SVG-images working for anyone? Tried it with two different images and only get a blank white page. Using the latest store-version.
