### ISSUE TITLE
[FR] Quick look folders inside

### ISSUE THREAD

**Issue by softyoda** [QL-Win/QuickLook#491]
Hello, I would like to know if it would be possible to add the support for previewing subfolders as it is for example the case on the SEER application currently.

**Comment by xupefei** [comment]
This can be supported technically but I have no plan to implement it. QuickLook is designed to republicate macOS Quick Look, and the latter has no such functionality.

Nevertheless, you can write a plugin to previrew folder contents. See https://github.com/QL-Win/QuickLook/wiki/Integration-and-Development for more details.

**Comment by adyanth** [comment]
Can this not be implemented from the Archive Viewer itself? 
Wont changing https://github.com/QL-Win/QuickLook/blob/6af2a5ec0d259e5eac7f295304657eff6da3fa74/QuickLook.Plugin/QuickLook.Plugin.ArchiveViewer/Plugin.cs#L41 to `return Directory.Exists(path) || (!Directory.Exists(path) && Extensions.Any(path.ToLower().EndsWith));` work? (Maybe would need slight modifications to not extract the zip if it is a directory)

I am not well versed with C# at all, but since it is implemented for the Archive Viewer, it is literally the same that needs to be shown.

What do you say @xupefei ?

**Comment by xupefei** [comment]
@adyanth Yeah the ArchiveViewer might be a good start, I believe some slight modifications can make it a folder previewer.
Feel free to do experimentations and add it to https://github.com/QL-Win/QuickLook/wiki/Available-Plugins when finished :)
