### ISSUE TITLE
Windows 10 May 2019 1903 Update Error

### ISSUE THREAD

**Issue by cklenk** [QL-Win/QuickLook#506]
I'm trying to upgrade to windows 10 1903 and keep getting this error in the event log:

Installation Failure: Windows failed to install the following update with error 0x80073D02: 9NV4BS3L1H4S-21090PaddyXu.QuickLook.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Pro 1809 Build 17763.529
 - QuickLook Version: 3.6.5 UWP

**Screenshots and Exception Log**
![image](https://user-images.githubusercontent.com/12185742/58524991-0f1bc100-8198-11e9-975b-4ec594485694.png)
![image](https://user-images.githubusercontent.com/12185742/58525013-2195fa80-8198-11e9-9579-d0944cfa7564.png)

**Comment by Bricolas** [comment]
On my computers, I have the next error since the May update 1903 (version 18932.1000)  
![2019-07-09_09-46-45](https://user-images.githubusercontent.com/14942122/60869470-53868c00-a22f-11e9-930b-dea259a1c439.png)


It seems to occur only for csv with this sing inside : "
[Test.zip](https://github.com/QL-Win/QuickLook/files/3376014/Test.zip)

**Comment by emako** [comment]
The problem is old and should be closed
