### ISSUE TITLE
WIN10启动的时候，会运行两个quicklook

### ISSUE THREAD

**Issue by uuair** [QL-Win/QuickLook#599]
![1](https://user-images.githubusercontent.com/2612307/72198047-7bb3a980-3463-11ea-9195-4a7c5ab2e7a2.png)
如果是一般用户运行，选择开机启动，会出现错误。
如果管理员权限，则无法开机启动。
如果把启动文件放到C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp
这里，则会开机的时候运行两个quicklook。

**Comment by JensenAGhost** [comment]
For all's convenience, please use English to fill this issue.

Please search within existing issues before the submission. Has this issue already been reported?

Describe the bug
A clear and concise description of what the bug is.

To Reproduce
Steps to reproduce the behavior:

Go to '...'
Click on '....'
Scroll down to '....'
See error
Expected behavior
A clear and concise description of what you expected to happen.

Desktop (please complete the following information):

OS Version: [e.g. Windows 10 1803]
QuickLook Version: [e.g. 0.3.3 from Windows Store]
Screenshots and Exception Log
If applicable, add screenshots and logs to help explain your problem. The log file is located in %APPDATA%\pooi.moe\QuickLook\QuickLook.Exception.log (.msi or .zip version) or %LOCALAPPDATA%\Packages\21090PaddyXu.QuickLook_egxr34yet59cg\LocalCache\Roaming\pooi.moe\QuickLook\QuickLook.Exception.log (Windows Store version).

**Comment by MC-dusk** [comment]
Excuse me, I have the same (or similar?) question.
Only when I start ***QuickLook*** in admin mode, can it turn on the option ***run while start*** (that's right), but it will show two items in ***Start*** in ***Task manager*** just as follow:
![image](https://user-images.githubusercontent.com/52311860/103146929-f72b6b00-4747-11eb-8231-1afd7ad88960.png)
Sorry for poor English...

**Comment by xupefei** [comment]
> Only when I start QuickLook in admin mode, can it turn on the option run while start

No, this is not right. QuickLook should now need to be running as admin to turn that option on.

Could you navigate to `C:\Users\[User Name]\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup` and delete anything related to QL?

**Comment by MC-dusk** [comment]
There is nothing in

>C:\Users\[User Name]\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup

But I find **QuickLook.ink** in

>C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup

and the start item of ***QuickLook*** in Task manager disappeared after I delete that...

**Comment by xupefei** [comment]
Then try to run QuickLook (**not** as admin), right-click on the taskbar icon, and check "Run on Startup".

**Comment by MC-dusk** [comment]
It can't turn on if not in admin.

**Comment by xupefei** [comment]
That's weird. Are you logged in using an Administrator account?

**Comment by MC-dusk** [comment]
yes

**Comment by xupefei** [comment]
Yes, it does. The Store version uses a different auto-startup mechamisim. I believe that's why you can see two items.

**Comment by MC-dusk** [comment]
What a pity... Since it doesn't cause any other trouble now, maybe I won't try to solve this problem. That's fine for me now.
Thank you for your replies.
