### ISSUE TITLE
Pixel-perfect previews for PNG and other image files

### ISSUE THREAD

**Issue by justinraymondpark** [QL-Win/QuickLook#610]
I love this app, it's essential for Windows. But it's not ideal for viewing small images designed for pixel art (for example, 16x16 or 32x32 dimensions). It appears to apply some kind of filter to the image, making it really blurry instead of crisp and clear.

It would be awesome to have the option to present these images accurately!
![HumphreyFlat01](https://user-images.githubusercontent.com/59776030/74308846-4dadd780-4d37-11ea-9542-a8d486b3050a.png) vs 
![32×32_ HumphreyFlat01 png 2020-02-12 01 30 35](https://user-images.githubusercontent.com/59776030/74308857-543c4f00-4d37-11ea-92ff-59c27f16259e.png)

**Comment by rabelux** [comment]
Confirming this issue and want to add that it displays a weird zoom level of `1,250 %` for a 16x16 png. The blurriness is probably no filter but the zoom level as initial zoom for a 32x32 is `625 %` for me.
I also have the issue of a minimum window size being to small, but I guess that's a different topic.
![grafik](https://user-images.githubusercontent.com/16120882/74343636-aa4ada00-4dab-11ea-86d4-21c25f6df419.png)

@xupefei what was the reason to zoom images to fit the window size? And I guess this behaviour can be changed by setting `private bool _zoomToFit = true` to `false` in `QuickLook.Plugin/QuickLook.Plugin.ImageViewer/ImagePanel.xaml.cs`?

**Comment by Darklocq** [comment]
Yeah, this is pretty severe.  I wouldn't want to see zooming disabled entirely, just no blurred like this.

**Comment by FeBe95** [comment]
I second this! Also, it would be nice to have a setting to disable zooming of small images in general. This should work for all images that fit on the screen (including some margin of ~5%). These should be displayed pixel-perfect (independent from Windows DPI settings).

### Example
- Screen size: 1920 x 1080
- image1.png size: 512 x 512
- image2.png size: 1024 x 1024
- image3.png size: 2048 x 2048

### Result
- image1 gets displayed at 100%, pixel perfect, because its dimensions fit on the screen (both width and height)
- image2's height is smaller than 1080 but there needs to be some space for the top bar of the QuickLook window and the Windows task bar etc., so render it at around 90%
- image3 is bigger than the display size, so shrink it down to ~45%, same behavior as with image2.png

Currently small images are mostly zoomed to 125% for me, probably because that's my dpi setting in Windows. That makes them blurry and unpleasant to look at.

**Comment by lucius346346** [comment]
Can confirm the same issue on my desktop. I have 1440p screen set to 125% scaling. All images looks blurry. Also smaller ones  are displayed 25% larger than they really are.

**Comment by xupefei** [comment]
Try this one: https://ci.appveyor.com/project/xupefei/quicklook/builds/32586205/artifacts

Now you should be able to change the zoom level to exactly 100%.

**Comment by jir5024** [comment]
Sooooo much better! thank you so much!

it does seem to max out at 300%, which for something like a 32x32 file is still pretty small - I wouldn't mind that being nudged up quite a lot. But this is soooo much better than it was, I'm not complaining :)

**Comment by lucius346346** [comment]
OK, now for some reason all images are rendered weirdly with this version. The edges are jagged.

![Screenshot_1](https://user-images.githubusercontent.com/43910504/80857649-fcd1bf00-8c53-11ea-9df2-afc27ee2dfe1.png)

**Comment by xupefei** [comment]
It’s because I have changed the scaling anti-aliasing quality from high to low. I’ll change it back.

**Comment by xupefei** [comment]
Is it better now?
https://ci.appveyor.com/project/xupefei/quicklook/builds/32619446/artifacts

**Comment by lucius346346** [comment]
Picture is smooth but it's displayed at 125% zoom by default.

**Comment by xupefei** [comment]
Yeah, the initial zoom is not 100%, but you are now able to adjust it to 100%.
