### ISSUE TITLE
The portable version should not use %APPDATA% for storing configs

### ISSUE THREAD

**Issue by xupefei** [QL-Win/QuickLook#731]
*For all's convenience, please use English to fill this issue.*

*Please search within existing issues before the submission. Has this issue already been reported?*

**Describe the bug**

**To Reproduce**
N/A

**Expected behavior**
See the title.

**Desktop (please complete the following information):**
 - OS Version: All versions
 - QuickLook Version: All portable versions

**Screenshots and Exception Log**
If applicable, add screenshots and logs to help explain your problem. The log file is located in `%APPDATA%\pooi.moe\QuickLook\QuickLook.Exception.log` (`.msi` or `.zip` version) or `%LOCALAPPDATA%\Packages\21090PaddyXu.QuickLook_egxr34yet59cg\LocalCache\Roaming\pooi.moe\QuickLook\QuickLook.Exception.log` (Windows Store version).

**Comment by just-Addict** [comment]
Let me add to this since just referring to the title is meh... 

**Describe the bug**
When running the so-called _portable_ version. The Config file and any user installed plugins end up in 
`%APPDATA%\pooi.moe\QuickLook\` (config)
`%APPDATA%\pooi.moe\QuickLook\QuickLook.Plugin` (plugins)

**To Reproduce**
unpack _portable_ version after un**b**locking (and not unlocking) 
run it and install some additional plugins.
Explore the above mentioned locations.
Find files there

**Expected behavior**
The concept of being portable means that any and ALL configuration files and additional files should be stored in the application's own folder or sub folders thereof. Using %APPDATA% does not only make the application not portable. It will partly cease to function as expected when actually used as a portable application on a USB medium and taken to another PC, because user installed plugins do not get included.


Desktop (please complete the following information):

OS Version: All versions
QuickLook Version: All portable versions
Screenshots and Exception Log
If applicable, add screenshots and logs to help explain your problem. The log file is located in %APPDATA%\pooi.moe\QuickLook\QuickLook.Exception.log (.msi or .zip version) or %LOCALAPPDATA%\Packages\21090PaddyXu.QuickLook_egxr34yet59cg\LocalCache\Roaming\pooi.moe\QuickLook\QuickLook.Exception.log (Windows Store version).
