### ISSUE TITLE
File scrolling with up and down arrows

### ISSUE THREAD

**Issue by albertopasqualetto** [QL-Win/QuickLook#917]
I would like to scroll a file pages using up and down arrows and not only the mouse wheel.
I think that if I open Quick look with the space key, I already have my hands on keyboard, so my suggestion would be a useful behaviour.

The way it is configured right now is, for me, redundant.

Thanks.

**Comment by rabelux** [comment]
QuickLook doesn't steal focus from the file explorer and therefore arrowkeys move file selection in the background. If you focus the preview window you can use <kbd>↑</kbd>/<kbd>↓</kbd> to scroll.

I understand that it might be useful for larger text-, office- and pdf-files to open the preview window in the foreground, but for all other files I'd the say the background-approach is the better one.

If you still want to avoid using the mouse simply press <kbd>enter</kbd> instead of <kbd>space</kbd> and use the default viewer

**Comment by albertopasqualetto** [comment]
Ok, I understand your point of view. Thanks!
