### ISSUE TITLE
!!! QuickLook is spying on my mailbox and outlook account

### ISSUE THREAD

**Issue by marcustone** [QL-Win/QuickLook#937]
Hi Paddyxu, please give me one good reason why my outlook ost files are copied to your app cache folder??
You want to preview my mailbox OST files for new updates?
I was astonished to find even if I deleted the OST in your app cache folder, it will soon show up again in there!!!
is this an expected behavior? What kind of logic is this, and why is QuickLook spying on user's private email communication??

Anyone there who suspects this please try to access your directory to check whether your outlook OST files are monitored by Paddyxu's Quicklook if you have local outlook account
C:\Users\[xxx]\AppData\Local\Packages\21090PaddyXu.QuickLook_egxr34yet59cg\LocalCache\Local\Microsoft\Outlook

Paddyxu, please explain, and are you from China?

**Comment by xupefei** [comment]
The path you provided is managed by UWP Sandbox, and files are copied by the sandbox. If you haven't ever tried to preview files from Outlook then it might be due to the [WoW64HookHelper](https://github.com/QL-Win/QuickLook/tree/master/QuickLook.Native/QuickLook.WoW64HookHelper) which injects itself into Outlook, which makes Windows thinks Outlook data should be sandboxed.

I believe this issue will go away if you use [ZIP or MSI versions](https://github.com/QL-Win/QuickLook/releases), which are not sandboxed.

> and are you from China?

Yes, I am -- why do this matters? QuickLook is fully open-source and you can examine every line of the codes. You should do some work before making an accusation.

**Comment by marcustone** [comment]
Please note that the OST file is not a mirror nor injection, it seems to be theft in regular period, not sure when the next theft is taking place, further details please see the screenshots to compare!
![Snipaste_2021-07-06_12-22-17](https://user-images.githubusercontent.com/17929904/124542305-bd08f780-de55-11eb-919f-15d6d30d0a4c.png)
![Snipaste_2021-07-06_12-22-19](https://user-images.githubusercontent.com/17929904/124542311-bed2bb00-de55-11eb-8660-1264370531c9.png)
