### ISSUE TITLE
New plugin for Office documents

### ISSUE THREAD

**Issue by xnsua** [QL-Win/QuickLook#94]
加密docx文件的预览导致崩溃

**Comment by xnsua** [comment]
xnsua

**Comment by xupefei** [comment]
The preview component provided by MS is truly a mess ...
I will rework it later.

**Comment by TaicEart** [comment]
预览 docx 需要 MSOffice 安装？_不可能安装的，这辈子都不可能安装的。_

是否可以试试调用 [pandoc](http://pandoc.org)？某软件利用这个的 docx2md、epub2text 功能达成对 docx、odt、epub 的简单预览，这就足够了。

**Comment by xupefei** [comment]
pandoc 只能读 docx 吧。pptx和 xlsx 就没办法了……

另外，pandoc 是 GPLv2协议的，那个软件内置 pandoc 违规了吧。看来还是没有吸取教训。

**Comment by TaicEart** [comment]
只读 docx 也是可以的。即使是文本形式。

那个倒是没内置到安装文件里，是另外提供 pandoc.exe 下载，以命令形式调用。

**Comment by bennyyip** [comment]
可以暂时禁用掉office文件的预览吗？

**Comment by xupefei** [comment]
删掉或移走 Plugin 目录下的 QuickLook.Plugin.IPreviewHandlers 目录。

**Comment by xupefei** [comment]
I have found that Syncfusion provides free Office viewer to open-source projects, however, since its license is not compatible with GPL, the new plugin will not be shipped out-of-box with QuickLook - users must download it manually from another place.

TODO: UWP is sandboxed where users are not able to access the appdata folder. Therefore, QuickLook should uncompress zipped plugin data into the userdata folder, and load it in the next run.

**Comment by xupefei** [comment]
I have contacted Syncfusion about the Community License. They agreed to give us a free license for their product, however, their agreement it says the follows:

> Customer acknowledges and agrees that if the Customer uses the Licensed product to create an open-source project, and then chooses to share that project with others, then Customer further acknowledges and agrees that the Customer will abide by the following additional terms concerning. Failure to abide by any of the following additional terms is a material breach of this Agreement which will result in immediate termination of all rights granted hereunder. Upon breach of this section titled “Open Source Project Terms,” then Customer is immediately liable for all damages caused directly or indirectly by Customer’s breach of this Agreement.
>  Customer must have a written agreement in place under which it grants rights to its Open Source Project, and such written agreement shall clearly state that any person or entity obtaining any Syncfusion code, licensed assemblies, or dependencies as a result of the Open Source Project must obtain their own licensed copy of the Licensed Product from Syncfusion.
>  Customer shall not distribute any Syncfusion binaries as part of an open-source project.
>  The open-source project will not be licensed under any viral code license or General Public License to include, but not be limited, to GNU or GPL. 
>  The open-source project can only be licensed under BSD or MIT licensing.

In my understanding, the above sentences mean that
* Any QuickLook user must apply for a separate license from Syncfusion.
* I can not release a binary distribution of QuickLook containing Syncfusion Dlls. The users must obtain these DLLs from elsewhere by themselves.

It does not make any sense for me to have a community license since I will not be able to release QuickLook anymore, and any of you (as users) will also need to do lots of complex works.

**Comment by KrasnayaPloshchad** [comment]
如果用 LibreOffice 会怎样？

**Comment by xupefei** [comment]
Does it provide Preview Handlers, or it only converts documents to for
example PDF?

**Comment by fqzhou** [comment]
[Feature Request] Preview eps/ps files as images #138
Currently, they are shown as text files. So what can I do if I wanna preview them as imaSorry for the rthe repost, because I cannot find the answer to #138 with it tagged closed.

**Comment by xupefei** [comment]
I have tested GemBox's free solution. It seems that it is usable.
I will release a package soon.
